# Generated by Django 3.1 on 2021-02-04 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspirations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, verbose_name='主题')),
                ('detail', models.TextField(verbose_name='细节')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '灵感',
                'verbose_name_plural': '灵感',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Diaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=8, verbose_name='天气')),
                ('mood', models.CharField(max_length=8, verbose_name='心情')),
                ('event', models.CharField(max_length=30, verbose_name='事件')),
                ('process', models.TextField(verbose_name='过程')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
                'ordering': ['date_created'],
            },
        ),
    ]
